INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (2, 'Ford', 'EcoSport', 'DEF5678', '2021', FALSE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (3, 'Volkswagen', 'Gol', 'GHI9012', '2019', TRUE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (4, 'Toyota', 'Corolla', 'JKL3456', '2018', FALSE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (5, 'Fiat', 'Uno', 'MNO7890', '2022', TRUE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (6, 'Renault', 'Kwid', 'PQR2345', '2020', FALSE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (7, 'Chevrolet', 'Cruze', 'STU6789', '2017', TRUE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (8, 'Honda', 'Civic', 'VWX1234', '2019', FALSE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (9, 'Hyundai', 'HB20', 'YZA5678', '2018', TRUE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (10, 'Nissan', 'March', 'BCD9012', '2021', FALSE);

INSERT INTO Veiculo (ID, MARCA, MODELO, PLACA, ANO, CHECK_IN_OUT)
VALUES (11, 'Ford', 'Fiesta', 'EFG3456', '2019', TRUE);
